# General
setw -g xterm-keys on
set -s escape-time 0
set -sg repeat-time 300
set -s focus-events on
set -g mouse on
set -sg exit-empty on
set -g extended-keys on

set -q -g status-utf8 on
setw -q -g utf8 on
set -g history-limit 5000

bind c new-window -c "#{pane_current_path}"

# Prefix
unbind C-b
set -g prefix 'C-a'

# Display
set-option -sa terminal-overrides ",xterm*:Tc"
set -g status-style "bg=#4e3362,fg=#dedc95"
set -g pane-active-border-style "fg=#dedc95"
set -g pane-border-style "fg=#4e3362"
setw -g window-status-current-style "fg=#4e3362,bg=#dedc95"
set -g base-index 1
setw -g pane-base-index 1

## image passthrough
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

setw -g automatic-rename on
set -g renumber-windows on

set -g set-titles on

set -g display-panes-time 2000
set -g display-time 2000

set -g default-terminal "tmux-256color"

# Window Navigation
unbind n
unbind p
bind Right next-window
bind Left previous-window

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

set -g mode-keys vi
